name: Deploy vite
on:
    push:
        # We only run this GitHub action upon new commits to `master`
        branches:
            - master
        # We only run this GitHub action if there are changes in the `src/` or `pages/` directories
        paths:
            - src/**
            - pages/**
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4

            - run: pnpm install
            - run: pnpm run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: docs/dist/client
                  # Remove previous build files
                  clean: true
                  # Do not remove the `.nojekyll` or `CNAME` files
                  clean-exclude: |
                      .nojekyll
                      CNAME
permissions:
    contents: write
